inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - bin/*
    - db/**/*
    - node_modules/**/*
    - vendor/**/*
  NewCops: enable
  TargetRubyVersion: 3.4.3
RSpec/PendingWithoutReason:
  Enabled: false
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 4
  Exclude:
    - spec/features/**/*
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
