version: '3'

services:
  app:
    build: .
    depends_on:
      - pg
      - redis
    env_file:
      - .env
    ports:
      - 3000:3000
  sidekiq:
    build: .
    depends_on:
      - pg
      - redis
    env_file:
      - .env
    command: sidekiq
    volumes:
      - /tmp:/storage
  pg:
    image: postgres:15.0-alpine
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  redis:
    image: redis:7.0.7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
