name: 'Setup Ruby Environment'
description: 'Sets up Ruby with bundler cache and common dependencies'
inputs:
  install-postgres-deps:
    description: 'Install PostgreSQL dependencies'
    required: false
    default: 'false'
  install-chrome:
    description: 'Install Chrome for system tests'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      if: inputs.install-postgres-deps == 'true' || inputs.install-chrome == 'true'
      shell: bash
      run: |
        sudo apt-get update
        if [ "${{ inputs.install-postgres-deps }}" == "true" ]; then
          sudo apt-get install -y libpq-dev
        fi
        if [ "${{ inputs.install-chrome }}" == "true" ]; then
          sudo apt-get install -y google-chrome-stable
        fi
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.5'
        bundler-cache: true
