default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  host: <%= ENV.fetch('IN_DOCKER', false) ? 'pg' : 'localhost' %>
  port: 5432
  encoding: unicode

development:
  <<: *default
  database: kudochest_dev
  min_messages: warning

test:
  <<: *default
  database: kudochest_test
  min_messages: error
  variables:
    statement_timeout: 90s

production:
  <<: *default
  host: <%= ENV.fetch('DB_HOST', nil) %>
  username: <%= ENV.fetch('DB_USER', nil) %>
  password: <%= ENV.fetch('DB_PASSWORD', nil) %>
  database: <%= ENV.fetch('DB_NAME', nil) %>
  pool: <%= ENV.fetch('DB_POOL', 20) %>
  checkout_timeout: 5
  reaping_frequency: 10
