name: RSpec
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: kudochest_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:6
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    env:
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/kudochest_test
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Ruby Environment
      uses: ./.github/actions/setup-ruby
      with:
        install-postgres-deps: 'true'
        install-chrome: 'true'
    - name: Setup database
      run: |
        bundle exec rails db:create
        bundle exec rails db:migrate
    - name: Precompile assets
      run: bundle exec rails assets:precompile
    - name: Run RSpec
      run: bundle exec rspec
